version: '3'

services:

  api-gateway:
    container_name: api-gateway-service
    build: .
    restart: unless-stopped
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    networks:
      - cloud-network

networks:
  cloud-network:
    name: cloud-network
